server:
  servlet:
    context-path: /api

spring:
  h2:
    console.enabled: true
    console.path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update